### PR TITLE
Fixing java agent download

### PR DESCRIPTION
**Pull request by Brunzer**

### CODE REVIEW

**Comment by djoos** [comment]
Hi @Brunzer,

any chance you could have a look at the failed tests related to the changes?
I'd also be great if you could take out the version bump (metadata) and changelog-changes in the PR...

Thanks in advance!
David

**Comment by Brunzer** [comment]
Hey @djoos 

I took a look at it seems to be failing looking for the jar file on centos, though the other checks seem to pass (I would imagine they would all fail if there was a real problem locating this?). I tried to start up a vm with test-kitchen to troubleshoot this a bit further but can't seem to get authentication going to it to even start converging. I'll keep trying when I get some time to see if I can resolve that but if you have any insight, that would be awesome.

I can also remove the version bump (sorry about that)

**Comment by djoos** [comment]
Hi,

no worries re: failing tests, I'm happy to have a look at that over the next few days.

Thanks for reverting the metadata and changelog (sorry, that's a real bugbear of mine! :-))

Have a great evening!
David

**Comment by Brunzer** [comment]
Haha no problem. Thanks for taking a look!

**Comment by djoos** [comment]
Thanks for your contribution @Brunzer!

Kind regards,
David

**Pull request merged**
