### PR TITLE
Make the default nil so we don't create an empty setting.

### PR DESCRIPTION
**Pull request by dipthegeezer**
The default is empty string which ends up creating an empty
setting variable. This just tidies that up so we don't
create the setting unless its been explicitly defined.

### CODE REVIEW

**Comment by djoos** [comment]
Hi @dipthegeezer,

thanks for re-pushing - I'll review ASAP!

Kind regards,
David

**Comment by dipthegeezer** [comment]
Hi 

Sorry to pester you again just wondering if I could get a review on this soon. 

Thanks

**Comment by dipthegeezer** [comment]
I have absolutely no idea why the build is failing, it seems unrelated to my changes. If you have some idea please let me  know.

**Comment by djoos** [comment]
Hi @dipthegeezer,

the failing build is unrelated to your changes - just checked them out and they seem good to go.

Thanks for your contribution!
David

**Pull request merged**
