### PR TITLE
updated version constraint for apt cookbook to resolves the error 

### PR DESCRIPTION
**Pull request by swapnil-jaiswal**
Error Details :
Could not satisfy version constraints for: yum ; when the recipe is executed on latest version of Amazon Linux 2016.03

### CODE REVIEW

**Comment by djoos** [comment]
Hi @swapnil-jaiswal,

I'd actually go for removing the version constraint completely, similar to the other dependencies.
What do you think?

Thanks!
David

**Comment by swapnil-jaiswal** [comment]
Yeah that was the first thing that came to my mind as well. 
But on the flip side keeping version constrains usually ensures that we have tested the complete functionality of the cookbook and all its dependencies till the particular version mentioned in constraints. Hence it is sort of a guarantee that the complete package will work with  the mentioned versions. So i think version constraints provide some sort of sanity to the code. 

We can however consider removing version constrains in case the cookbook it depends have a faster cycle of release than its own to ensure that end user mostly gets a working copy of code.

**Comment by hlarsen** [comment]
hey all,

seeing the same error writing a cookbook, looks like this commit will solve it - it's been a while, thoughts on merging?

**Comment by shortdudey123** [comment]
@djoos any feedback on your end? or can this get merged in?

**Comment by djoos** [comment]
I'm actually still in favor of removing the version constraint completely...

@swapnil-jaiswal: if you could update the PR I'll get this merged in ASAP!

**Comment by djoos** [comment]
Thanks for your contribution @swapnil-jaiswal - merged! I'll push out a patch release shortly...

**Pull request merged**
