### PR TITLE
add distributed tracing to php agent resource

### PR DESCRIPTION
**Pull request by ls-brentsmith**
Add distributed tracing options to php agent resource.

* `'distributed_tracing_enabled'` - Defaults to false
* `'distributed_tracing_exclude_newrelic_header'` - Default to false

### CODE REVIEW

**Comment by ls-brentsmith** [comment]
@djoos How do you like to handle the cookbook versioning on PRs?

**Comment by djoos** [comment]
Hi @ls-brentsmith,

please leave the changelog and cookbook versioning bits - https://github.com/djoos-cookbooks/newrelic/blob/master/CONTRIBUTING.md#metadatarb

Hope this helps!

**Comment by ls-brentsmith** [comment]
@djoos done

**Comment by djoos** [comment]
Thanks for your contribution @ls-brentsmith!

**Pull request merged**
